### ISSUE TITLE
VM display doesn't automatically re-size at first boot

### ISSUE THREAD

**Issue by cnotin** [flesueur/mi-lxc#21]
I use the latest .ova (that you provided) with latest VBox 6.1.14
The first time I start the VM the display isn't properly automatically re-sized to my real screen size, despite this option being enabled.
It only works after a reboot. Any idea why?

**Comment by flesueur** [comment]
It's a "known bug". You need to play a bit with the window size (not fullscreen, using the window corner) and, after 1 or 2 movements it starts working...
I'll try to replace the video controller to see if it behaves better !

**Comment by cnotin** [comment]
(Give me back my VMware workstation!)
Ok lol :)
If we can’t find a workaround maybe we need to write this down somewhere

**Comment by flesueur** [comment]
It's the same with vmsvga. I think the VM needs to "validate" something. Clearly, I'll explain it in the TP (I usually tell it in the room...).
I let this issue open until I modify the TP...
